[package]
name = "proxmox-backup-qemu"
version = "1.0.3"
authors = [
    "Dietmar Maurer <dietmar@proxmox.com>",
    "Dominik Csapak <d.csapak@proxmox.com>",
    "Fabian Gr√ºnbichler <f.gruenbichler@proxmox.com>",
    "Stefan Reiter <s.reiter@proxmox.com>",
    "Thomas Lamprecht <t.lamprecht@proxmox.com>",
    "Wolfgang Bumiller <w.bumiller@proxmox.com>",
]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ['lib', 'cdylib', 'staticlib']

[build-dependencies]
cbindgen = "0.14.2"

[dependencies]
anyhow = "1.0"
bytes = "1.0"
futures = "0.3"
h2 = { version = "0.3", features = [ "stream" ] }
lazy_static = "1.4"
libc = "0.2"
once_cell = "1.5"
openssl = "0.10"
proxmox = { version = "0.10.5", features = [ "sortable-macro", "api-macro" ] }
#proxmox = { path = "../proxmox/proxmox" }
proxmox-backup = { git = "git://git.proxmox.com/git/proxmox-backup.git", tag = "v1.0.8" }
#proxmox-backup = { path = "../proxmox-backup" }
serde_json = "1.0"
tokio = { version = "1.0", features = [ "fs", "io-util", "macros", "net", "rt-multi-thread", "signal", "time" ] }
tokio-stream = "0.1.1"
bincode = "1.0"
